### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by IvanJasenov** [cs50/harvard.cs50.hex#1]
What is the purpose of the hex? Is there analogy between what the hexdump do in applications like Wireshark?

**Comment by kzidane** [comment]
This plugin basically allows for opening hex representation for files (a la xxd from pset4), but with a nice, simple GUI.

![hex](https://cloud.githubusercontent.com/assets/7230211/19009275/4d551520-8772-11e6-81b8-ec677650e292.png)

**Comment by IvanJasenov** [comment]
Looks nice! Did something like this for FTP on the server side but in "raw" C.
