### ISSUE TITLE
Switch editor or force-open?

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.hex#2]
@dmalan, by default, if you "Open Hex" a file that's already open with another editor, it just activates the tab where that file is open (without switching the editor).

Two options here
1. switch editor (possibly after the user confirms)
2. force-open the file with the hex editor in a new tab (e.g., two tabs, with diff editors, for the same file would be open)

What do you think would be a better UX here?

**Comment by dmalan** [comment]
Hm, 2 seems a bit cleaner, especially since the hex viewer can (should) be read-only anyway?

**Comment by kzidane** [comment]
Closing as supported per 20e66da4! Unfortunately though, the other way around (i.e., opening in default editor when already open in hex) is not as easy.

Perhaps we'll have to try listen for clicking "Open", and do that ourselves, since the C9's tree plugin (which [adds](https://github.com/c9/core/blob/master/plugins/c9.ide.tree/tree.js#L556) "Open") doesn't do that.
